config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :street, type: String
  field :city, type: String
  field :state, type: String

  embeds_in :addresses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :street, :city, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MongoPeople</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :person_name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :person_street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :person_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :person_state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.street %></td>
        <td><%= person.city %></td>
        <td><%= person.state %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>